import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { UserProvider } from "./context/usercontext";
import { CartProvider } from "./context/cartcontext";
import Footer from "./footer/page"; // Import Footer component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Wrap children with UserProvider and CartProvider to provide contexts */}
        <UserProvider>
          <CartProvider>
            <main className="flex-grow">{children}</main>
            <Footer /> {/* Include Footer at the bottom */}
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
