# Define the name of the workflow
name: Ecom-Shop CI/CD

# Specify the events that will trigger the workflow
on:
  push: # Trigger the workflow on push events
    branches:
      - main # Trigger only on pushes to the main branch
  pull_request: # Trigger the workflow on pull request events
    branches:
      - main # Main branch pull requests

# Define jobs to run in the workflow
jobs:
  build-and-test: # Job to build and test the application
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for the job
    strategy:
      matrix:
        node-version: [18.20.4] # Specify the Node.js version to use

    env:
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js "${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"

      - name: Clean environment
        run: |
          cd isolora
          rm -f package-lock.json

      - name: Install dependencies
        run: |
          cd isolora
          yarn install

      - name: Build
        run: |
          cd isolora
          yarn build || (echo "Build failed. See logs above." && exit 1)

      - name: Run tests
        run: |
          cd isolora
          yarn test

  deploy: # Job to deploy the application
    needs: build-and-test # Ensure this job runs only if build-and-test succeeds
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    strategy:
      matrix:
        node-version: [18.20.4] # Use the same Node.js version as the build job

    env:
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js "${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"

      - name: Install dependencies
        run: |
          cd isolora
          yarn install

      - name: Build
        run: |
          cd isolora
          yarn build || (echo "Build failed. See logs above." && exit 1)

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Link Vercel Project
        run: |
          cd isolora
          vercel link --yes --token $VERCEL_TOKEN --project ecom-shop-9ty2

      - name: Deploy to Vercel
        run: |
          cd isolora
          vercel --prod --yes --token $VERCEL_TOKEN
